config/routes.rb
Rails.application.routes.draw do
  resource :dashboard, only: [:show]
  root to: "dashboards#show"

  resources :lists
  resources :members, only: [:index, :create, :destroy], defaults: { format: :json }
  resources :friends, only: [:index]
  resource :session do
    get :callback
  end

end

app/models/list.rb
class ListWithMembers
  include ActiveModel::Model
  include Twitter::REST::Lists
  attr_accessor :list
end

app/models/list_with_members.rb
class ListWithMembers
  include ActiveModel::Model
  include Twitter::REST::Lists
  attr_accessor :list, :members

  def members
    @members ||= twitter.list_members(list, count: 200)
  end

  private

    def twitter
      @twitter ||= Twitter::REST::Client.new do |config|
        config.consumer_key = ENV["CONSUMER_KEY"]
        config.consumer_secret = ENV["CONSUMER_SECRET"]
        config.access_token = ENV["ACCESS_TOKEN"]
        config.access_token_secret = ENV["ACCESS_TOKEN_SECRET"]
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  FRIENDS_COUNT = (ENV["FRIENDS_COUNT"] || 200).to_i

  private

    def login_required
      unless session[:access_token]
        redirect_to new_session_path
      end
    end

    def twitter
      @twitter ||= Twitter::REST::Client.new do |config|
        config.consumer_key = ENV["CONSUMER_KEY"]
        config.consumer_secret = ENV["CONSUMER_SECRET"]
        config.access_token = session[:access_token]
        config.access_token_secret = session[:access_token_secret]
      end
    end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :login_required

  def show
    response = twitter.friends(cursor: params[:cursor], count: FRIENDS_COUNT)
    gon.next = response.attrs[:next_cursor]
    gon.friends = @friends = response.take(FRIENDS_COUNT)
    lists = twitter.lists.sort_by(&:name)
    @lists = lists.map {|l| ListWithMembers.new(list: l) }
    gon.list_members = @lists.map do |l|
      {
        list: l.list,
        members: [],
        completed: false,
      }
    end
    gon.current_user_id = twitter.user.id
  end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  def index
    response = twitter.friends(cursor: params[:cursor], count: FRIENDS_COUNT)
    @friends = response.take(FRIENDS_COUNT)
    @next = response.attrs[:next_cursor]
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :login_required

  def index
    member_id_lists = twitter.list_members(list_id: params[:list_id], owner_id: params[:owner_id], count: 200).map {|m| m.to_h[:id_str] }
    render json: member_id_lists
  end

  def create
    twitter.add_list_member(member_params[:list].to_i, member_params[:user].to_i)
    render nothing: true
  end

  def destroy
    twitter.remove_list_member(member_params[:list].to_i, member_params[:user].to_i)
    render nothing: true
  end

  private

    def member_params
      params.require(:member).permit(:list, :user)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    request_token = oauth_client.request_token(oauth_callback: callback_url)
    session[:request_token] = request_token.token
    session[:request_token_secret] = request_token.secret
    redirect_to request_token.authorize_url
  end

  def callback
    access_token = oauth_client.authorize(
      session[:request_token],
      session[:request_token_secret],
      oauth_verifier: params[:oauth_verifier],
    )
    session[:access_token] = access_token.token
    session[:access_token_secret] = access_token.secret
    redirect_to root_path
  end

  private

    def callback_url
      host = ENV["HOST"] || "http://localhost:3000"
      File.join(host, "/session/callback")
    end

    def oauth_client
      @oauth_client ||= TwitterOAuth::Client.new(
        consumer_key: ENV["CONSUMER_KEY"],
        consumer_secret: ENV["CONSUMER_SECRET"],
      )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboards/show.html.slim
h1 TODO: Display account name here.

#user-in-list
  user v-for="user in users" :user="user" :list-members="listMembers"
  .col-md-4
    .next-box
      div v-if="fetching"
        i.fa.fa-spinner.fa-spin.fa-3x
      div(v-else)
        button.btn.btn-primary @click.prevent="fetchNext"
          | Next

script type="x/template" id="user"
  .col-md-4
    .user-box.panel.panel-default
      .user-profile-wrap
        .user-profile
          img :src="user.profile_image_url"
          br
          | @{{ user.screen_name }}
      .member-of-list
        ul.list-group
          list v-for="l in listMembers" :list="l.list" :members="l.members" :user="user" :completed="l.completed"

script type="x/template" id="list"
  li.list-group-item
    .checkbox
      label
        div v-if="completed"
          input type="checkbox" v-model="checked" @click="checkedChanged"
          | {{ list.name }}
        div(v-else)
          span.label.label-primary
            | Loading...

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "TwitterListEditor"
    = include_gon
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"
    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"


  body
    .navbar.navbar-default.navbar-static-top
        .container
          button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse"
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.navbar-brand href="#"TwitterListEditor
          .navbar-collapse.collapse.navbar-responsive-collapse
            ul.nav.navbar-nav

    .container
      .row
        .col-lg-12
          = bootstrap_flash
          = yield

      footer
        p

app/views/layouts/error.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "TwitterListEditor"
    = include_gon
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"
    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"


  body
    .navbar.navbar-default.navbar-static-top
        .container
          button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse"
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.navbar-brand href="#"TwitterListEditor
          .navbar-collapse.collapse.navbar-responsive-collapse
            ul.nav.navbar-nav

    .container
      .row
        .col-lg-12
          = yield

      footer
        p

app/views/lists/index.html.slim
h1 Listing lists

table.table
  thead
    tr
      th user
      - @lists.each do |list|
        th = list.name

  tbody
    - @friends.each do |user|
      tr
        td
          = "@#{user.screen_name}"
          = image_tag user.profile_image_url
        - @lists.each do |list|
          td ◯
= link_to "Next", lists_path(cursor: @next)